import { SelfRepairProposal, RootCauseAnalysisReport, CapabilityRiskLevel } from '../../shared/types';
import { debugSandboxEngine } from './debugSandboxEngine';

class SelfRepairEngine {
  private proposals = new Map<string, SelfRepairProposal>();

  public generateProposal(
    incidentId: string,
    rcaReport: RootCauseAnalysisReport
  ): SelfRepairProposal {
    const proposalId = `repair_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    const category: SelfRepairProposal['category'] =
      rcaReport.primaryErrorCategory === 'TIMEOUT' || rcaReport.primaryErrorCategory === 'RATE_LIMITED'
        ? 'RECONFIG_TIMEOUT'
        : rcaReport.primaryErrorCategory === 'PROVIDER_UNAVAILABLE'
        ? 'FALLBACK_CAPABILITY'
        : 'RETRY_WITH_BACKOFF';

    const proposedAction = {
      actionType: category,
      targetComponent: rcaReport.earliestCausalSpan?.component || 'SYSTEM',
      parameterUpdates: {
        timeoutMs: 12000,
        retryAttempts: 3,
        backoffMultiplier: 1.5,
      },
    };

    // Run isolated sandbox simulation first
    const sandboxResult = debugSandboxEngine.runSandboxSimulation(incidentId, proposedAction);

    const proposal: SelfRepairProposal = {
      proposalId,
      incidentId,
      title: `Self-Repair Proposal: ${category} for ${incidentId}`,
      category,
      targetComponent: rcaReport.earliestCausalSpan?.component || 'SYSTEM',
      description: `Automated repair plan generated by DeepDiagnosticsEngine: Apply ${category} to resolve root cause ${rcaReport.fingerprint}.`,
      proposedAction,
      riskLevel: 'MEDIUM' as CapabilityRiskLevel,
      simulationResult: {
        success: sandboxResult.success,
        simulatedImpact: sandboxResult.simulatedImpact,
        predictedRecoveryPct: sandboxResult.predictedRecoveryPct,
      },
      status: 'PROPOSED',
      governanceApprovalRequired: true,
      createdAt: new Date().toISOString(),
      rollbackPlan: {
        rollbackAction: 'RESTORE_PREVIOUS_CONFIG',
        rollbackData: {
          previousTimeoutMs: 5000,
          previousRetryAttempts: 1,
        },
      },
    };

    this.proposals.set(proposalId, proposal);
    return proposal;
  }

  public getProposal(proposalId: string): SelfRepairProposal | undefined {
    return this.proposals.get(proposalId);
  }

  public getAllProposals(): SelfRepairProposal[] {
    return Array.from(this.proposals.values());
  }

  public approveProposal(proposalId: string, approvedBy = 'Operator / Governance Supervisor'): SelfRepairProposal {
    const proposal = this.proposals.get(proposalId);
    if (!proposal) throw new Error(`Repair proposal ${proposalId} not found.`);

    proposal.status = 'APPROVED';
    proposal.approvedBy = approvedBy;

    return proposal;
  }

  public applyProposal(proposalId: string): SelfRepairProposal {
    const proposal = this.proposals.get(proposalId);
    if (!proposal) throw new Error(`Repair proposal ${proposalId} not found.`);

    if (proposal.governanceApprovalRequired && proposal.status !== 'APPROVED') {
      throw new Error(`Governed Self-Repair ${proposalId} requires explicit approval before application.`);
    }

    proposal.status = 'APPLIED';
    proposal.appliedAt = new Date().toISOString();

    return proposal;
  }

  public rollbackProposal(proposalId: string): SelfRepairProposal {
    const proposal = this.proposals.get(proposalId);
    if (!proposal) throw new Error(`Repair proposal ${proposalId} not found.`);

    if (proposal.status !== 'APPLIED') {
      throw new Error(`Cannot rollback proposal ${proposalId} as it is not currently APPLIED.`);
    }

    proposal.status = 'ROLLED_BACK';
    proposal.rollbackAt = new Date().toISOString();

    return proposal;
  }
}

export const selfRepairEngine = new SelfRepairEngine();
